### ISSUE TITLE
Typo in example in README.md

### ISSUE THREAD

**Issue by yhenon** [RSIA-LIESMARS-WHU/LSHBOX#2]
There seems to be a typo in the provided example in the README.md file at line 51:
```c
    for (int I = 0; i != Q; ++i)
```
Should be

```c
    for (int i = 0; i != Q; ++i)
```
Thank you for the work on the library.

**Comment by IenLong** [comment]
Hello,
Thank you very much for using LSHBOX and give us feedback.
We have checked  and modified the  README.md file.  
Please do not hesitate to contact us if there is any other question.
----- Original Message -----

**Comment by yhenon** [comment]
Thanks for fixing this.
