### ISSUE TITLE
Matrix shallow copy 

### ISSUE THREAD

**Issue by patpatbear** [RSIA-LIESMARS-WHU/LSHBOX#5]
Matrix<TYPE> should not be copyable  , may be the default copy ctor should be deleted

**Comment by IenLong** [comment]
Why  the Matrix should not be copyable? Could you describe it more clearly?

**Comment by IenLong** [comment]
It's kind of you to give us advice.
We have rewrite the copy constructor and assignment operator.
Thank you for your attention to LSHBOX.

**Comment by patpatbear** [comment]
you guys rock!!
