### ISSUE TITLE
Python module fails to compile

### ISSUE THREAD

**Issue by yhenon** [RSIA-LIESMARS-WHU/LSHBOX#6]
I'm attempting to compile LSHBOX with python. The compilation completes when using only the C++ module. I have the boost include headers in the path, using gcc on ubuntu 14.04.
I get the following error

    /home/ubuntu/LSHBOX/python/pylshbox.cpp: In member function ‘boost::python::list lshbox::pyRbsLsh::query(boost::python::list&, unsigned int, unsigned int)’:
    /home/ubuntu/LSHBOX/python/pylshbox.cpp:138:79: error: conversion from ‘std::vector<std::pair<float, unsigned int>, std::allocator<std::pair<float, unsigned int> > >’ to non-scalar type ‘std::vector<std::pair<unsigned int, float> >’ requested
         std::vector<std::pair<unsigned, float> > tmp = scanner.topk().getTopk();

The error is repeated several times for the other algorithms. I've been able to compile this in the past, maybe related to some of the recent changes ?
Best.

**Comment by primetang** [comment]
Thank you very much for your feedback. Now, the error has been fixed. Happy try again!

**Comment by csjzy1234** [comment]
support lshbox python3?

**Comment by xiaozf** [comment]
Not yet. 

 

We haven’t enough time, and hope someone can help us to do it.

 

 

发件人: csjzy1234 [mailto:notifications@github.com] 
发送时间: 2017年3月12日 5:52
收件人: RSIA-LIESMARS-WHU/LSHBOX
抄送: Subscribed
主题: Re: [RSIA-LIESMARS-WHU/LSHBOX] Python module fails to compile (#6)

 

support lshbox python3?
