### ISSUE TITLE
kdbqlsh.h   save and load function has bug.

### ISSUE THREAD

**Issue by duming** [RSIA-LIESMARS-WHU/LSHBOX#8]
It seems that the save and load function in kdbqlsh.h is a copy of the same functions in dbqlsh.
u0, u1, and u2 are missing from these two functions.  
If you save the index and then load it back, the index won't work.

**Comment by IenLong** [comment]
We have rewritten these functions and now you can try it again.
Thanks for your attention to LSHBOX!
