### ISSUE TITLE
bug in kdbqlsh.h

### ISSUE THREAD

**Issue by duming** [RSIA-LIESMARS-WHU/LSHBOX#9]
In function 
`void lshbox::kdbqLsh<DATATYPE>::DataProjectoin()`

The two matrix multiplication iteration blocks seems wrong.
I guess the code here are designed to do matrix multiplications, but mess up the array subscripts.

```c++
for (unsigned i = 0; i != X.rows(); ++i)
        {
            for (unsigned q = 0; q != param.N; ++q)
            {
                float sum = 0.0;
                for (unsigned j = 0; j != X.cols(); ++j)
                {
                    sum += X(i, j) * pcsAll[k][q][j];//bug here
                }
                prj(i, q) = sum;
            }
        }
```

**Comment by IenLong** [comment]
Everything works well by our local tests. 
Feel free to contact us if there is any other question.
Thank you very much for your attention to LSHBOX!
